const ACTION_TYPE  = {
    GET_POPULAR : "GET_POPULAR",
    GET_TOP_CAST : "GET_TOP_CAST",
    GET_FULL_URL_IMG : "GET_FULL_URL_IMG",
    GET_POPULAR_DETAIL : "GET_POPULAR_DETAIL",
    GET_SEARCH: "GET_SEARCH",
}

export default ACTION_TYPE;